version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: hackathon
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=default
    volumes:
      - /Users/macbook/me/hackathon/db:/var/lib/mysql
