openapi: 3.0.0
info:
  title: Author API
  version: 1.0.0
tags:
  - name: authors
    description: Operations about authors
paths:
  /authors/{id}:
    get:
      tags:
        - authors
      summary: Get an author by ID
      operationId: getAuthorById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
        '404':
          description: Author not found
components:
  schemas:
    Author:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        birthDate:
          type: string
          format: date